# -*- coding: utf-8 -*-
"""predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5L2OmtCeRPvkZ8tOzP4N4PoZgDJZmj8
"""

import os
import joblib
import numpy as np
import pandas as pd


class FraudRiskPredictor:

  def __init__(self, bundle_path: str = "fraud_model.joblib"):
    if not os.path.exists(bundle_path):
      raise FileNotFoundError(
          f"Required model bundle not found at {bundle_path}. Please run"
          " train.py first."
      )
    bundle = joblib.load(bundle_path)
    self.calibrator = bundle["calibrator"]
    self.explainer = bundle["explainer"]
    self.features = bundle["features"]

  def evaluate_transaction(self, request_payload: dict) -> dict:
    """Accepts inbound request schema matching POST /api/v1/intercept.

    Returns risk_assessment components: fraud_probability and
    shap_attributions.
    """
    telemetry = request_payload.get("telemetry", {})

    # Extract and cast the exact 7 contract features with safe defaults
    feature_row = {
        "amount_inr": float(request_payload.get("amount_inr", 0.0)),
        "active_call": 1 if telemetry.get("active_call") else 0,
        "call_duration_seconds": int(
            telemetry.get("call_duration_seconds") or 0
        ),
        "screen_share_active": (
            1 if telemetry.get("screen_share_active") else 0
        ),
        "typing_jitter_ms": float(
            telemetry.get("typing_jitter_ms")
            if telemetry.get("typing_jitter_ms") is not None
            else 60.0
        ),
        "is_new_payee": 1 if telemetry.get("is_new_payee_for_payer") else 0,
        "velocity_10m": int(telemetry.get("transactions_in_last_10m") or 1),
    }

    input_df = pd.DataFrame([feature_row])[self.features]

    # 1. Platt-calibrated fraud probability
    fraud_prob = float(self.calibrator.predict_proba(input_df)[0, 1])

    # 2. TreeSHAP feature attributions
    shap_raw = self.explainer.shap_values(input_df)
    if isinstance(shap_raw, list):
      vals = shap_raw[1][0]
    elif getattr(shap_raw, "ndim", 0) == 2:
      vals = shap_raw[0]
    else:
      vals = shap_raw

    # Map raw features to the contract SHAP keys used by frontend/Red-Team
    key_mapping = {
        "active_call": "prolonged_active_voice_call",
        "amount_inr": "new_beneficiary_high_amount",
        "velocity_10m": "payee_in_degree_velocity_burst",
        "typing_jitter_ms": "typing_hesitation_jitter",
        "screen_share_active": "screen_share_surveillance",
        "call_duration_seconds": "voice_call_duration_risk",
        "is_new_payee": "unverified_new_payee",
    }

    shap_attributions = {
        key_mapping.get(feat, feat): round(float(val), 4)
        for feat, val in zip(self.features, vals)
    }

    return {
        "fraud_probability": round(fraud_prob, 4),
        "shap_attributions": shap_attributions,
    }


if __name__ == "__main__":
  predictor = FraudRiskPredictor()
  sample_payload = {
      "transaction_id": "TXN_UPI_20260911_8941203",
      "timestamp": "2026-09-11T13:45:12.104Z",
      "payer": {
          "account_id": "ACC_HDFC_9182310293",
          "vpa": "user.sharma@okhdfcbank",
          "phone": "+919876543210",
          "device_id": "DEV_SAMSUNG_S24_F1920A",
      },
      "payee": {
          "account_id": "ACC_CANARA_0921829102",
          "vpa": "fast.verify.services@okaxis",
          "ifsc": "CNRB0001928",
      },
      "amount_inr": 42500.00,
      "currency": "INR",
      "telemetry": {
          "active_call": True,
          "call_duration_seconds": 1840,
          "call_ended_seconds_ago": None,
          "screen_share_active": False,
          "accessibility_service_enabled": False,
          "typing_speed_wpm": 84.0,
          "typing_jitter_ms": 142.0,
          "is_new_payee_for_payer": True,
          "transactions_in_last_10m": 1,
      },
  }

  result = predictor.evaluate_transaction(sample_payload)
  print("Inference output against Contract Section 3.2:")
  print(result)