#!/usr/bin/env python3
"""
Interloc Unified Startup Orchestrator.

Boots both the FastAPI Core Interceptor Switch and the Next.js
Bank Operations Command Center concurrently with automated
local environment configuration and graceful process teardown.

Usage:
    python start.py
"""

import os
import sys
import time
import shutil
import signal
import socket
import subprocess
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
FRONTEND_DIR = BASE_DIR / "frontend"
BACKEND_DIR = BASE_DIR / "backend"


def is_port_in_use(port: int, host: str = "127.0.0.1") -> bool:
    """Checks if a local TCP port is already bound."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.5)
        return s.connect_ex((host, port)) == 0


def ensure_local_environments() -> None:
    """Auto-generates local .env files if not present."""
    fe_env = FRONTEND_DIR / ".env.local"
    if not fe_env.exists():
        fe_env.write_text(
            "# Auto-generated by start.py for local development\n"
            "NEXT_PUBLIC_API_URL=http://localhost:8000\n",
            encoding="utf-8",
        )
        print("[*] Created frontend/.env.local (NEXT_PUBLIC_API_URL=http://localhost:8000)")

    be_env = BACKEND_DIR / ".env"
    if not be_env.exists():
        be_env.write_text(
            "# Auto-generated by start.py for local development\n"
            "HOST=0.0.0.0\n"
            "PORT=8000\n"
            "DEBUG=false\n"
            "SLA_BUDGET_MS=45.0\n",
            encoding="utf-8",
        )
        print("[*] Created backend/.env with default switch settings")


def verify_prerequisites() -> None:
    """Checks Python version and Node/npm tools."""
    if sys.version_info < (3, 10):
        print("[ERROR] Python 3.10 or higher is required.")
        sys.exit(1)

    npm_path = shutil.which("npm") or shutil.which("npm.cmd")
    if not npm_path:
        print("[ERROR] Node.js and npm are required for the frontend. Please install Node.js.")
        sys.exit(1)

    # Check if frontend dependencies are installed
    if not (FRONTEND_DIR / "node_modules").exists():
        print("[*] Installing frontend dependencies (npm install)...")
        subprocess.run([npm_path, "install"], cwd=str(FRONTEND_DIR), check=True)


def main() -> None:
    print("\n" + "=" * 60)
    print("  INTERLOC LOCAL SWITCH COMMAND CENTER")
    print("=" * 60)

    verify_prerequisites()
    ensure_local_environments()

    # Port checks
    if is_port_in_use(8000):
        print("[WARNING] Port 8000 is already in use. Ensure no previous backend is running.")
    if is_port_in_use(3000):
        print("[WARNING] Port 3000 is already in use. Ensure no previous frontend is running.")

    npm_bin = shutil.which("npm.cmd") if os.name == "nt" else shutil.which("npm")
    if not npm_bin:
        npm_bin = "npm"

    # Child process environments
    be_env = os.environ.copy()
    be_env["PYTHONUNBUFFERED"] = "1"

    fe_env = os.environ.copy()
    fe_env["NEXT_PUBLIC_API_URL"] = "http://localhost:8000"

    processes: list[subprocess.Popen] = []

    try:
        print("[*] Spawning FastAPI Switch Core on port 8000...")
        backend_proc = subprocess.Popen(
            [sys.executable, "-m", "uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"],
            cwd=str(BASE_DIR),
            env=be_env,
        )
        processes.append(backend_proc)

        # Brief pause to let backend bind port
        time.sleep(1.0)

        print("[*] Spawning Next.js Command Center on port 3000...")
        frontend_proc = subprocess.Popen(
            [npm_bin, "run", "dev"],
            cwd=str(FRONTEND_DIR),
            env=fe_env,
        )
        processes.append(frontend_proc)

        print("\n" + "=" * 60)
        print("  INTERLOC LOCAL CLUSTER READY")
        print("=" * 60)
        print("  Frontend Console:       http://localhost:3000")
        print("  Backend API Docs:       http://localhost:8000/docs")
        print("  Liveness Probe:         http://localhost:8000/health")
        print("  Decision Stream:        http://localhost:8000/api/v1/stream/decisions")
        print("=" * 60)
        print("  Press Ctrl+C to terminate all services cleanly.\n")

        # Monitor loop
        while True:
            for proc in processes:
                exit_code = proc.poll()
                if exit_code is not None:
                    print(f"[!] Process {proc.args} exited unexpectedly with code {exit_code}")
                    return
            time.sleep(1)

    except KeyboardInterrupt:
        print("\n[*] Received shutdown signal. Gracefully terminating all processes...")
    finally:
        for proc in processes:
            try:
                proc.terminate()
                proc.wait(timeout=3)
            except Exception:
                try:
                    proc.kill()
                except Exception:
                    pass
        print("[*] All local switch services stopped cleanly.")


if __name__ == "__main__":
    main()
